site_name: sd-mecha
theme:
  name: material
  features:
    - content.code.copy
extra_css:
  - style.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js
  - javascripts/mathjax_config.js
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('sd_mecha')
markdown_extensions:
  - extra
  - tables
  - mdx_math:
      enable_dollar_delimiter: True
      use_gitlab_delimiters: True
  - fenced_code
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      inline_syntax: [true]
      generic: true
